CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_roles WHERE rolname = 'root'
   ) THEN
      CREATE ROLE root WITH LOGIN PASSWORD 'root' CREATEDB;
   END IF;
END
$$;
SELECT 'CREATE DATABASE app_local OWNER "root" ENCODING "UTF8" LC_COLLATE "en_US.utf8" LC_CTYPE "en_US.utf8" TABLESPACE pg_default CONNECTION LIMIT-1'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'app_local')\gexec
ALTER USER root SUPERUSER;
 
